apiVersion: apps/v1
kind: Deployment
metadata:
  name: bus-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bus
  template:
    metadata:
      labels:
        app: bus
    spec:
      containers:
        - name: bus
          image: thanadilok/bus
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: MONGO_URI
              value: "mongodb://bus-mongo-srv:27017/bus"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: bus-srv
spec:
  selector:
    app: bus
  ports:
    - name: bus
      protocol: TCP
      port: 3000
      targetPort: 3000
